### ISSUE TITLE
[Feature request] Add alternating backdrop to mod config items

### ISSUE THREAD

**Issue by dfgHiatus** [badhaloninja/NeosModSettings#2]
I sometimes find it difficult to read mod config items line by line, especially when looking at a list of booleans:

![unity](https://user-images.githubusercontent.com/51272212/183141926-52b8851a-f57d-481a-b8af-9e8741e92278.PNG)

It would be nice to have an alternating backdrop for each of these items, similar to how [SettingsRedux](https://github.com/XDelta/SettingsRedux/releases) does things:

![settings](https://user-images.githubusercontent.com/51272212/183141922-1a36eddb-f1ef-4dd7-88a7-2d42a7e94de1.PNG)

**Comment by badhaloninja** [comment]
Added in [v1.3.0](https://github.com/badhaloninja/NeosModSettings/releases/tag/v1.3.0)
