### ISSUE TITLE
[bug report] nullables show but cant be made null.

### ISSUE THREAD

**Issue by EIA485** [badhaloninja/NeosModSettings#4]

**Comment by badhaloninja** [comment]
this appears to be an issue of NeosModLoader's key validation function 
I have made an issue [here](https://github.com/neos-modding-group/NeosModLoader/issues/78)

**Comment by EIA485** [comment]
ive confirmed that [neos-modding-group/NeosModLoader/ #79](https://github.com/neos-modding-group/NeosModLoader/pull/79) fixed the issue by testing against [Toxic-Cookie/GenericSettings](https://github.com/Toxic-Cookie/GenericSettings)
