### ISSUE TITLE
[feature request] suport for flag enums

### ISSUE THREAD

**Issue by EIA485** [badhaloninja/NeosModSettings#5]
currently nms will display a stranded enum selector regardless of if the enum is a flag enum or not. would be nice to be able to toggle each element of the enum via ui.

**Comment by badhaloninja** [comment]
Does this solve your problem?
https://github.com/badhaloninja/EnumDropdown

**Comment by badhaloninja** [comment]
Solved by adding to [EnumDropdown](https://github.com/badhaloninja/EnumDropdown)
