### ISSUE TITLE
[Bug] Reset Default Settings button does not reset internal access only config keys if they are not currently visible

### ISSUE THREAD

**Issue by Nytra** [badhaloninja/NeosModSettings#8]
Internal keys should always be reset by this button even if they are not visible.

**Comment by badhaloninja** [comment]
I did not want this to be default behavior as it could mess with some mods
Now it will only clear internal access only if you enable it in the options, and it will reset them even if they are hidden

[v1.3.0](https://github.com/badhaloninja/NeosModSettings/releases/tag/v1.3.0)
