### ISSUE TITLE
[Bug] Reset Default Settings button does not trigger ModConfiguration.OnThisConfigurationChanged event

### ISSUE THREAD

**Issue by Nytra** [badhaloninja/NeosModSettings#9]
I'm adding a feature to my mod and I want things to happen when the config changes. It works normally but when I click the Reset Default Settings button it seems to not fire the event at all.

**Comment by badhaloninja** [comment]
Fixed in [v1.3.0](https://github.com/badhaloninja/NeosModSettings/releases/tag/v1.3.0)
